Rectify typographical inaccuracies.
nexus-xyz/nexus-zkvm pull request #190
Opened 2024-06-17 16:07 UTC by nnsW3

This PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.

**Justification**
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.

2024-06-18 17:23 UTC, mx00s commented on docs/pages/specs/zkvm-overview.mdx
> +[[GWC19](https://eprint.iacr.org/2019/953)] Ariel Gabizon, Zachary J Williamson, and Oana Ciobotaru. “Plonk: Permutations over lagrange-bases for oecumenical non-interactive arguments of knowledge”.
We should stick with the actual title of the paper. It uses "noninteractive" without a hyphen.

The BibTeX on the linked page indicates the title should be as follows:

```suggestion
[[GWC19](https://eprint.iacr.org/2019/953)] Ariel Gabizon, Zachary J Williamson, and Oana Ciobotaru. “PLONK: Permutations over Lagrange-bases for Oecumenical Noninteractive arguments of Knowledge”. In: Cryptology ePrint Archive (2019)
```

2024-06-18 17:24 UTC, mx00s requested changes
Thanks for the PR.

I offered a small suggestion, but otherwise LGTM.

2024-06-18 20:23 UTC, nnsW3 commented
good sugestion thanks

2024-06-20 11:52 UTC, nnsW3 commented
already made the changes? could you merge?

2024-06-28 08:44 UTC, closed without merging