Re-export postcard in runtime
nexus-xyz/nexus-zkvm pull request #280
Opened 2024-08-21 21:53 UTC by evan-schott

Re-exports `postcard` in `runtime` crate to ensure consistent serialization between host, guest and prover.

Resolves #277.

2024-08-21 22:44 UTC, sjudson requested changes

2024-08-21 22:44 UTC, sjudson commented on cli/src/command/host.rs
> -    // add postcard because it is used for (de)serializing from/to the input/output tapes
We want to leave this in for now to not break existing programs. We can remove it eventually.

2024-08-22 17:12 UTC, duc-nx commented on runtime/Cargo.toml
> +postcard = { version = "1.0.10", features = ["alloc"] }
we use postcard for no-std env. Can you also add `default_features=False`?

2024-08-22 17:12 UTC, duc-nx commented on sdk/Cargo.toml
> +postcard = { version = "1.0.10", features = ["alloc"] }
we use postcard for no-std env. Can you also add `default_features=False`?

2024-08-22 18:12 UTC, sjudson requested changes

2024-08-22 18:12 UTC, sjudson commented on runtime/src/lib.rs
> +pub use postcard::*;
It would probably be preferable to just do `pub use postcard`, and have users access through `nexus_rt::postcard` to be clear what's going on here.

2024-08-22 19:26 UTC, sjudson approved these changes

2024-08-22 19:28 UTC, merged