fix: ensure witness size is power of two
nexus-xyz/nexus-zkvm pull request #338
Opened 2024-12-27 01:20 UTC by DeVikingMark

Fixes #287

Added check to ensure witness size is power of two in `CRR1CSProof::prove()` function to prevent potential index out of bounds error when reading from empty vector.

Changes made:
- Added assertion to check if witness size is power of two
- Added descriptive error message for better debugging

This prevents the issue where reading index of zero from an empty vector could occur if the witness size is not a power of two.

2025-01-21 15:10 UTC, sjudson approved these changes
Thanks for this, looks good to me.

2025-01-21 15:12 UTC, sjudson requested changes
Withdrawing acceptance till pending tests are fixed, but overall design still looks good.

2025-01-23 13:56 UTC, sjudson commented
@DeVikingMark what is the reason for removing an existing test?

2025-02-26 00:26 UTC, DeVikingMark commented
Hey Samuel, I've made a change:

- Fixed the clippy warning in vm/src/eval.rs by replacing map_or with is_some_and

Note: The cargo clippy command shows errors related to the pprof library on Windows, but these are unrelated to my code changes.

2025-02-26 15:11 UTC, sjudson commented
@DeVikingMark can you answer:

> what is the reason for removing an existing test?

2025-02-26 16:32 UTC, DeVikingMark commented
> @DeVikingMark can you answer:
> 
> > what is the reason for removing an existing test?

@sjudson I've deleted them by accident, and forgot to add it, sorry that's my fault

I've made some updates, probably now everything should be fine, I'll be waiting for tests to be completed

2025-02-27 15:59 UTC, sjudson requested changes
Almost there, but there is still some inconsistent indentation.

2025-02-28 14:11 UTC, sjudson approved these changes
LGTM pending tests passing...

2025-02-28 14:36 UTC, sjudson commented
@DeVikingMar clippy + fmt lints are still failing

2025-02-28 14:50 UTC, DeVikingMark commented
@sjudson Could it be that these errors are not related to my changes and were here before my intervention?

2025-03-06 18:43 UTC, sjudson commented
Given our rewrite of the codebase for the new Nexus 3.0 machine (https://github.com/nexus-xyz/nexus-zkvm/pull/365) I'm going to close as stale, but we greatly appreciate the contribution.

2025-03-06 18:43 UTC, closed without merging